"""add_series_type_and_character_profile_to_series

Revision ID: 583df7238d9b
Revises: 9c83e51af792
Create Date: 2026-05-29 19:10:15.536424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '583df7238d9b'
down_revision: Union[str, None] = '9c83e51af792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('series_type', sa.String(length=50), server_default='regular', nullable=False))
    op.add_column('series', sa.Column('character_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'character_profile')
    op.drop_column('series', 'series_type')
    # ### end Alembic commands ###
