"""add is_serialized to series

Revision ID: 9c83e51af792
Revises: 001
Create Date: 2026-05-29 19:02:19.609831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c83e51af792'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'caption_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'full_sentence'::character varying"))
    op.alter_column('publish_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('series', 'is_serialized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('series', 'schedule_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('series', 'schedule_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=False,
               existing_server_default=sa.text("'09:00'::character varying"))
    op.alter_column('series', 'caption_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'full_sentence'::character varying"))
    op.create_index(op.f('ix_series_user_id'), 'series', ['user_id'], unique=False)
    op.create_index(op.f('ix_series_episodes_series_id'), 'series_episodes', ['series_id'], unique=False)
    op.alter_column('users', 'videos_generated',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'videos_generated',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_series_episodes_series_id'), table_name='series_episodes')
    op.drop_index(op.f('ix_series_user_id'), table_name='series')
    op.alter_column('series', 'caption_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'full_sentence'::character varying"))
    op.alter_column('series', 'schedule_time',
               existing_type=sa.VARCHAR(length=5),
               nullable=True,
               existing_server_default=sa.text("'09:00'::character varying"))
    op.alter_column('series', 'schedule_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('series', 'is_serialized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('publish_jobs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('projects', 'caption_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'full_sentence'::character varying"))
    # ### end Alembic commands ###
